"""
Prompt templates for LLM operations

CHÚ Ý: Module này CHỈ export các prompt templates (constants).
Không export functions - logic build prompt nằm trong base_adapter.py
"""
from .quiz_prompts import (
    # Language instructions
    LANGUAGE_INSTRUCTIONS,
    LANGUAGE_INSTRUCTIONS_ALL,
    LANGUAGE_INSTRUCTIONS_SHORT,
    LANGUAGE_INSTRUCTIONS_TF,
    
    # Variety hints
    VARIETY_HINTS,
    
    # Prompt templates
    MCQ_PROMPT_TEMPLATE,
    BATCH_MCQ_PROMPT_TEMPLATE,
    DISTRACTOR_PROMPT_TEMPLATE,
    SHORT_ANSWER_PROMPT_TEMPLATE,
    TRUE_FALSE_PROMPT_TEMPLATE,
    
    # Instruction texts
    SINGLE_CHOICE_INSTRUCTION,
    MULTIPLE_CHOICE_INSTRUCTION_TEMPLATE,
    SINGLE_ANSWER_FORMAT,
    MULTIPLE_ANSWER_FORMAT,
    TYPE_INSTRUCTION_SINGLE,
    TYPE_INSTRUCTION_MULTIPLE,
    TYPE_INSTRUCTION_MIX,
    ANSWER_FORMAT_SINGLE,
    ANSWER_FORMAT_MULTIPLE,
    ANSWER_FORMAT_MIX,
    AVOID_DUPLICATION_TEMPLATE,
)

__all__ = [
    # Language instructions
    "LANGUAGE_INSTRUCTIONS",
    "LANGUAGE_INSTRUCTIONS_ALL",
    "LANGUAGE_INSTRUCTIONS_SHORT",
    "LANGUAGE_INSTRUCTIONS_TF",
    
    # Variety hints
    "VARIETY_HINTS",
    
    # Prompt templates
    "MCQ_PROMPT_TEMPLATE",
    "BATCH_MCQ_PROMPT_TEMPLATE",
    "DISTRACTOR_PROMPT_TEMPLATE",
    "SHORT_ANSWER_PROMPT_TEMPLATE",
    "TRUE_FALSE_PROMPT_TEMPLATE",
    
    # Instruction texts
    "SINGLE_CHOICE_INSTRUCTION",
    "MULTIPLE_CHOICE_INSTRUCTION_TEMPLATE",
    "SINGLE_ANSWER_FORMAT",
    "MULTIPLE_ANSWER_FORMAT",
    "TYPE_INSTRUCTION_SINGLE",
    "TYPE_INSTRUCTION_MULTIPLE",
    "TYPE_INSTRUCTION_MIX",
    "ANSWER_FORMAT_SINGLE",
    "ANSWER_FORMAT_MULTIPLE",
    "ANSWER_FORMAT_MIX",
    "AVOID_DUPLICATION_TEMPLATE",
]
